apiVersion: v1
kind: Service
metadata:
  name: backend-app
  labels:
    app: to-be-replaced-by-kustomization
spec:
  selector:
    app: to-be-replaced-by-kustomization
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9010