apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: backend-webhook-receiver
spec:
  port:
    targetPort: 8080
  to:
    name: el-backend-webhook-receiver
    kind: Service
    weight: 100